import type { VocabWord } from "./types";

// Subset of Oxford 3000 words organized by category
// Reference: Oxford 3000™ – the most important words to know in English

export const OXFORD_WORDS: VocabWord[] = [
  // ─── Daily Life (25) ──────────────────────────────────────
  {
    word: "arrange",
    phonetic: "/əˈreɪndʒ/",
    thaiMeaning: "จัด, จัดการ",
    partOfSpeech: "v.",
    examples: [
      "Can we arrange a meeting for tomorrow?",
      "She arranged the flowers in a vase.",
    ],
    category: "daily-life",
  },
  {
    word: "available",
    phonetic: "/əˈveɪləbl/",
    thaiMeaning: "ว่าง, มีอยู่, หาได้",
    partOfSpeech: "adj.",
    examples: [
      "Are you available this afternoon?",
      "This product is available in three colors.",
    ],
    category: "daily-life",
  },
  {
    word: "borrow",
    phonetic: "/ˈbɒrəʊ/",
    thaiMeaning: "ยืม",
    partOfSpeech: "v.",
    examples: [
      "Can I borrow your pen for a moment?",
      "She borrowed some money from the bank.",
    ],
    category: "daily-life",
  },
  {
    word: "convenient",
    phonetic: "/kənˈviːniənt/",
    thaiMeaning: "สะดวก",
    partOfSpeech: "adj.",
    examples: [
      "Is this a convenient time to call you?",
      "The hotel is in a convenient location near the station.",
    ],
    category: "daily-life",
  },
  {
    word: "decide",
    phonetic: "/dɪˈsaɪd/",
    thaiMeaning: "ตัดสินใจ",
    partOfSpeech: "v.",
    examples: [
      "I can't decide what to wear.",
      "They decided to get married in June.",
    ],
    category: "daily-life",
  },
  {
    word: "depend",
    phonetic: "/dɪˈpend/",
    thaiMeaning: "ขึ้นอยู่กับ",
    partOfSpeech: "v.",
    examples: [
      "It depends on the weather.",
      "Children depend on their parents.",
    ],
    category: "daily-life",
  },
  {
    word: "expect",
    phonetic: "/ɪkˈspekt/",
    thaiMeaning: "คาดหวัง, คาดว่า",
    partOfSpeech: "v.",
    examples: ["I expect to arrive by 6 pm.", "What do you expect me to do?"],
    category: "daily-life",
  },
  {
    word: "manage",
    phonetic: "/ˈmænɪdʒ/",
    thaiMeaning: "จัดการ",
    partOfSpeech: "v.",
    examples: [
      "How do you manage to stay so calm?",
      "She manages a team of ten people.",
    ],
    category: "daily-life",
  },
  {
    word: "prepare",
    phonetic: "/prɪˈpeə/",
    thaiMeaning: "เตรียม",
    partOfSpeech: "v.",
    examples: [
      "She is preparing dinner for the guests.",
      "You should prepare for the exam.",
    ],
    category: "daily-life",
  },
  {
    word: "suggest",
    phonetic: "/səˈdʒest/",
    thaiMeaning: "แนะนำ",
    partOfSpeech: "v.",
    examples: [
      "I suggest we leave early.",
      "Can you suggest a good restaurant?",
    ],
    category: "daily-life",
  },
  {
    word: "allow",
    phonetic: "/əˈlaʊ/",
    thaiMeaning: "อนุญาต",
    partOfSpeech: "v.",
    examples: [
      "Smoking is not allowed here.",
      "My parents allow me to stay out late.",
    ],
    category: "daily-life",
  },
  {
    word: "avoid",
    phonetic: "/əˈvɔɪd/",
    thaiMeaning: "หลีกเลี่ยง",
    partOfSpeech: "v.",
    examples: [
      "Try to avoid heavy traffic.",
      "She avoids eating sugary foods.",
    ],
    category: "daily-life",
  },
  {
    word: "belong",
    phonetic: "/bɪˈlɒŋ/",
    thaiMeaning: "เป็นของ",
    partOfSpeech: "v.",
    examples: ["This book belongs to me.", "Where does this belong?"],
    category: "daily-life",
  },
  {
    word: "compare",
    phonetic: "/kəmˈpeə/",
    thaiMeaning: "เปรียบเทียบ",
    partOfSpeech: "v.",
    examples: [
      "Compare the prices before you buy.",
      "People often compare me to my sister.",
    ],
    category: "daily-life",
  },
  {
    word: "consider",
    phonetic: "/kənˈsɪdə/",
    thaiMeaning: "พิจารณา",
    partOfSpeech: "v.",
    examples: [
      "I'm considering changing my job.",
      "You should consider all the options.",
    ],
    category: "daily-life",
  },
  {
    word: "contain",
    phonetic: "/kənˈteɪn/",
    thaiMeaning: "บรรจุ, มี",
    partOfSpeech: "v.",
    examples: [
      "This drink contains a lot of sugar.",
      "The box contains old photographs.",
    ],
    category: "daily-life",
  },
  {
    word: "continue",
    phonetic: "/kənˈtɪnjuː/",
    thaiMeaning: "ดำเนินต่อไป",
    partOfSpeech: "v.",
    examples: [
      "Please continue with your story.",
      "The rain continued all day.",
    ],
    category: "daily-life",
  },
  {
    word: "describe",
    phonetic: "/dɪˈskraɪb/",
    thaiMeaning: "บรรยาย",
    partOfSpeech: "v.",
    examples: [
      "Can you describe the man you saw?",
      "She described her experience in detail.",
    ],
    category: "daily-life",
  },
  {
    word: "encourage",
    phonetic: "/ɪnˈkʌrɪdʒ/",
    thaiMeaning: "ให้กำลังใจ",
    partOfSpeech: "v.",
    examples: [
      "My teacher encouraged me to apply.",
      "Parents should encourage their children.",
    ],
    category: "daily-life",
  },
  {
    word: "explain",
    phonetic: "/ɪkˈspleɪn/",
    thaiMeaning: "อธิบาย",
    partOfSpeech: "v.",
    examples: [
      "Can you explain how this works?",
      "She explained the problem to me.",
    ],
    category: "daily-life",
  },
  {
    word: "imagine",
    phonetic: "/ɪˈmædʒɪn/",
    thaiMeaning: "จินตนาการ",
    partOfSpeech: "v.",
    examples: [
      "Imagine living on a tropical island.",
      "I can't imagine life without her.",
    ],
    category: "daily-life",
  },
  {
    word: "include",
    phonetic: "/ɪnˈkluːd/",
    thaiMeaning: "รวม",
    partOfSpeech: "v.",
    examples: [
      "Does the price include breakfast?",
      "The tour includes a visit to the museum.",
    ],
    category: "daily-life",
  },
  {
    word: "mention",
    phonetic: "/ˈmenʃn/",
    thaiMeaning: "กล่าวถึง",
    partOfSpeech: "v.",
    examples: [
      "Did she mention anything about the meeting?",
      "He mentioned your name several times.",
    ],
    category: "daily-life",
  },
  {
    word: "realize",
    phonetic: "/ˈrɪəlaɪz/",
    thaiMeaning: "ตระหนัก",
    partOfSpeech: "v.",
    examples: [
      "I realized I had made a mistake.",
      "Do you realize how late it is?",
    ],
    category: "daily-life",
  },
  {
    word: "require",
    phonetic: "/rɪˈkwaɪə/",
    thaiMeaning: "ต้องการ",
    partOfSpeech: "v.",
    examples: [
      "This job requires a lot of patience.",
      "The form requires your signature.",
    ],
    category: "daily-life",
  },

  // ─── Food & Drink (20) ────────────────────────────────────
  {
    word: "bitter",
    phonetic: "/ˈbɪtə/",
    thaiMeaning: "ขม",
    partOfSpeech: "adj.",
    examples: [
      "This coffee tastes bitter.",
      "The medicine has a bitter taste.",
    ],
    category: "food-drink",
  },
  {
    word: "delicious",
    phonetic: "/dɪˈlɪʃəs/",
    thaiMeaning: "อร่อย",
    partOfSpeech: "adj.",
    examples: ["This cake is absolutely delicious!", "The meal was delicious."],
    category: "food-drink",
  },
  {
    word: "flavor",
    phonetic: "/ˈfleɪvə/",
    thaiMeaning: "รสชาติ",
    partOfSpeech: "n.",
    examples: [
      "Which flavor of ice cream do you want?",
      "This sauce has a spicy flavor.",
    ],
    category: "food-drink",
  },
  {
    word: "fresh",
    phonetic: "/freʃ/",
    thaiMeaning: "สด",
    partOfSpeech: "adj.",
    examples: [
      "I love fresh bread in the morning.",
      "The vegetables are very fresh.",
    ],
    category: "food-drink",
  },
  {
    word: "ingredient",
    phonetic: "/ɪnˈɡriːdiənt/",
    thaiMeaning: "ส่วนผสม",
    partOfSpeech: "n.",
    examples: [
      "What are the main ingredients in this dish?",
      "Mix all the ingredients together.",
    ],
    category: "food-drink",
  },
  {
    word: "spicy",
    phonetic: "/ˈspaɪsi/",
    thaiMeaning: "เผ็ด",
    partOfSpeech: "adj.",
    examples: ["This curry is very spicy.", "Do you like spicy food?"],
    category: "food-drink",
  },
  {
    word: "starving",
    phonetic: "/ˈstɑːvɪŋ/",
    thaiMeaning: "หิวมาก",
    partOfSpeech: "adj.",
    examples: ["I'm starving! When is dinner?", "Let's eat — I'm starving."],
    category: "food-drink",
  },
  {
    word: "taste",
    phonetic: "/teɪst/",
    thaiMeaning: "รสชาติ, ชิม",
    partOfSpeech: "n./v.",
    examples: ["The soup has a strange taste.", "Can I taste the sauce?"],
    category: "food-drink",
  },
  {
    word: "appetite",
    phonetic: "/ˈæpɪtaɪt/",
    thaiMeaning: "ความอยากอาหาร",
    partOfSpeech: "n.",
    examples: [
      "I have a big appetite today.",
      "Exercise gives me a good appetite.",
    ],
    category: "food-drink",
  },
  {
    word: "bake",
    phonetic: "/beɪk/",
    thaiMeaning: "อบ",
    partOfSpeech: "v.",
    examples: ["I'm going to bake a cake.", "Bake the bread for 30 minutes."],
    category: "food-drink",
  },
  {
    word: "boil",
    phonetic: "/bɔɪl/",
    thaiMeaning: "ต้ม",
    partOfSpeech: "v.",
    examples: [
      "Boil the water before adding the pasta.",
      "She boiled some eggs for breakfast.",
    ],
    category: "food-drink",
  },
  {
    word: "crispy",
    phonetic: "/ˈkrɪspi/",
    thaiMeaning: "กรอบ",
    partOfSpeech: "adj.",
    examples: [
      "I love crispy fried chicken.",
      "The toast is perfectly crispy.",
    ],
    category: "food-drink",
  },
  {
    word: "grill",
    phonetic: "/ɡrɪl/",
    thaiMeaning: "ย่าง",
    partOfSpeech: "v.",
    examples: [
      "Let's grill some burgers outside.",
      "Grill the fish for about five minutes.",
    ],
    category: "food-drink",
  },
  {
    word: "juicy",
    phonetic: "/ˈdʒuːsi/",
    thaiMeaning: "ฉ่ำ, มีน้ำ",
    partOfSpeech: "adj.",
    examples: [
      "This steak is so juicy and tender.",
      "The oranges are sweet and juicy.",
    ],
    category: "food-drink",
  },
  {
    word: "leftovers",
    phonetic: "/ˈleftəʊvəz/",
    thaiMeaning: "อาหารที่เหลือ",
    partOfSpeech: "n.",
    examples: [
      "We can eat the leftovers for lunch.",
      "Put the leftovers in the fridge.",
    ],
    category: "food-drink",
  },
  {
    word: "ripe",
    phonetic: "/raɪp/",
    thaiMeaning: "สุก",
    partOfSpeech: "adj.",
    examples: [
      "These bananas are not ripe yet.",
      "Pick the tomatoes when they are ripe.",
    ],
    category: "food-drink",
  },
  {
    word: "salty",
    phonetic: "/ˈsɔːlti/",
    thaiMeaning: "เค็ม",
    partOfSpeech: "adj.",
    examples: [
      "The soup is too salty.",
      "I prefer salty snacks over sweet ones.",
    ],
    category: "food-drink",
  },
  {
    word: "sour",
    phonetic: "/ˈsaʊə/",
    thaiMeaning: "เปรี้ยว",
    partOfSpeech: "adj.",
    examples: ["This lemon is very sour.", "The milk has gone sour."],
    category: "food-drink",
  },
  {
    word: "thirsty",
    phonetic: "/ˈθɜːsti/",
    thaiMeaning: "กระหายน้ำ",
    partOfSpeech: "adj.",
    examples: [
      "I'm so thirsty after running.",
      "Are you thirsty? Have some water.",
    ],
    category: "food-drink",
  },
  {
    word: "appetizer",
    phonetic: "/ˈæpɪtaɪzə/",
    thaiMeaning: "อาหารเรียกน้ำย่อย",
    partOfSpeech: "n.",
    examples: [
      "We ordered an appetizer to share.",
      "The appetizer was delicious.",
    ],
    category: "food-drink",
  },

  // ─── Travel (20) ──────────────────────────────────────────
  {
    word: "abroad",
    phonetic: "/əˈbrɔːd/",
    thaiMeaning: "ต่างประเทศ",
    partOfSpeech: "adv.",
    examples: [
      "She has never been abroad.",
      "Many students choose to study abroad.",
    ],
    category: "travel",
  },
  {
    word: "accommodation",
    phonetic: "/əˌkɒməˈdeɪʃn/",
    thaiMeaning: "ที่พัก",
    partOfSpeech: "n.",
    examples: [
      "We need to find accommodation for the night.",
      "The accommodation was very comfortable.",
    ],
    category: "travel",
  },
  {
    word: "arrival",
    phonetic: "/əˈraɪvl/",
    thaiMeaning: "การมาถึง",
    partOfSpeech: "n.",
    examples: [
      "Please wait for me in the arrival hall.",
      "The arrival time is scheduled for 3 pm.",
    ],
    category: "travel",
  },
  {
    word: "destination",
    phonetic: "/ˌdestɪˈneɪʃn/",
    thaiMeaning: "จุดหมายปลายทาง",
    partOfSpeech: "n.",
    examples: [
      "We finally reached our destination.",
      "What's your dream travel destination?",
    ],
    category: "travel",
  },
  {
    word: "luggage",
    phonetic: "/ˈlʌɡɪdʒ/",
    thaiMeaning: "กระเป๋าเดินทาง",
    partOfSpeech: "n.",
    examples: [
      "How much luggage do you have?",
      "I lost my luggage at the airport.",
    ],
    category: "travel",
  },
  {
    word: "passenger",
    phonetic: "/ˈpæsɪndʒə/",
    thaiMeaning: "ผู้โดยสาร",
    partOfSpeech: "n.",
    examples: [
      "All passengers must fasten their seatbelts.",
      "The bus can carry up to 50 passengers.",
    ],
    category: "travel",
  },
  {
    word: "reservation",
    phonetic: "/ˌrezəˈveɪʃn/",
    thaiMeaning: "การจอง",
    partOfSpeech: "n.",
    examples: [
      "I have a reservation under my name.",
      "Please confirm your reservation before arrival.",
    ],
    category: "travel",
  },
  {
    word: "sightseeing",
    phonetic: "/ˈsaɪtsiːɪŋ/",
    thaiMeaning: "การเที่ยวชม",
    partOfSpeech: "n.",
    examples: [
      "We went sightseeing in Paris.",
      "There's a sightseeing bus tour at noon.",
    ],
    category: "travel",
  },
  {
    word: "boarding",
    phonetic: "/ˈbɔːdɪŋ/",
    thaiMeaning: "การขึ้นเครื่อง",
    partOfSpeech: "n.",
    examples: [
      "Boarding will begin in 10 minutes.",
      "Please have your boarding pass ready.",
    ],
    category: "travel",
  },
  {
    word: "cancel",
    phonetic: "/ˈkænsl/",
    thaiMeaning: "ยกเลิก",
    partOfSpeech: "v.",
    examples: [
      "I need to cancel my flight.",
      "The concert was canceled due to rain.",
    ],
    category: "travel",
  },
  {
    word: "currency",
    phonetic: "/ˈkʌrənsi/",
    thaiMeaning: "สกุลเงิน",
    partOfSpeech: "n.",
    examples: [
      "What currency do they use in Japan?",
      "You can exchange currency at the bank.",
    ],
    category: "travel",
  },
  {
    word: "departure",
    phonetic: "/dɪˈpɑːtʃə/",
    thaiMeaning: "การออกเดินทาง",
    partOfSpeech: "n.",
    examples: [
      "The departure gate has changed.",
      "Please check the departure time.",
    ],
    category: "travel",
  },
  {
    word: "explore",
    phonetic: "/ɪkˈsplɔː/",
    thaiMeaning: "สำรวจ",
    partOfSpeech: "v.",
    examples: [
      "We spent the day exploring the city.",
      "I love to explore new places.",
    ],
    category: "travel",
  },
  {
    word: "foreign",
    phonetic: "/ˈfɒrɪn/",
    thaiMeaning: "ต่างประเทศ",
    partOfSpeech: "adj.",
    examples: [
      "She speaks two foreign languages.",
      "Do you enjoy travelling to foreign countries?",
    ],
    category: "travel",
  },
  {
    word: "guide",
    phonetic: "/ɡaɪd/",
    thaiMeaning: "ไกด์, นำทาง",
    partOfSpeech: "n./v.",
    examples: [
      "The tour guide was very knowledgeable.",
      "He guided us through the forest.",
    ],
    category: "travel",
  },
  {
    word: "journey",
    phonetic: "/ˈdʒɜːni/",
    thaiMeaning: "การเดินทาง",
    partOfSpeech: "n.",
    examples: [
      "The journey took about four hours.",
      "Life is a journey, not a destination.",
    ],
    category: "travel",
  },
  {
    word: "passport",
    phonetic: "/ˈpɑːspɔːt/",
    thaiMeaning: "หนังสือเดินทาง",
    partOfSpeech: "n.",
    examples: ["Don't forget your passport!", "My passport expires next year."],
    category: "travel",
  },
  {
    word: "souvenir",
    phonetic: "/ˌsuːvəˈnɪə/",
    thaiMeaning: "ของที่ระลึก",
    partOfSpeech: "n.",
    examples: [
      "I bought a souvenir for my sister.",
      "The market sells lots of souvenirs.",
    ],
    category: "travel",
  },
  {
    word: "tourist",
    phonetic: "/ˈtʊərɪst/",
    thaiMeaning: "นักท่องเที่ยว",
    partOfSpeech: "n.",
    examples: [
      "The city is full of tourists in summer.",
      "Are you a tourist here?",
    ],
    category: "travel",
  },
  {
    word: "voyage",
    phonetic: "/ˈvɔɪɪdʒ/",
    thaiMeaning: "การเดินทางทางเรือ",
    partOfSpeech: "n.",
    examples: [
      "The voyage across the ocean took two weeks.",
      "They went on a voyage around the world.",
    ],
    category: "travel",
  },

  // ─── Work & Business (22) ─────────────────────────────────
  {
    word: "achieve",
    phonetic: "/əˈtʃiːv/",
    thaiMeaning: "บรรลุ, ทำสำเร็จ",
    partOfSpeech: "v.",
    examples: [
      "She worked hard to achieve her goal.",
      "What do you hope to achieve this year?",
    ],
    category: "work-business",
  },
  {
    word: "application",
    phonetic: "/ˌæplɪˈkeɪʃn/",
    thaiMeaning: "ใบสมัคร",
    partOfSpeech: "n.",
    examples: [
      "Please fill out this application form.",
      "I sent my application last week.",
    ],
    category: "work-business",
  },
  {
    word: "colleague",
    phonetic: "/ˈkɒliːɡ/",
    thaiMeaning: "เพื่อนร่วมงาน",
    partOfSpeech: "n.",
    examples: [
      "I went to lunch with a colleague.",
      "My colleagues are very supportive.",
    ],
    category: "work-business",
  },
  {
    word: "deadline",
    phonetic: "/ˈdedlaɪn/",
    thaiMeaning: "กำหนดส่ง",
    partOfSpeech: "n.",
    examples: [
      "The deadline is next Monday.",
      "I'm working late to meet the deadline.",
    ],
    category: "work-business",
  },
  {
    word: "opportunity",
    phonetic: "/ˌɒpəˈtjuːnəti/",
    thaiMeaning: "โอกาส",
    partOfSpeech: "n.",
    examples: [
      "This is a great opportunity for you.",
      "Don't miss this opportunity.",
    ],
    category: "work-business",
  },
  {
    word: "responsibility",
    phonetic: "/rɪˌspɒnsəˈbɪləti/",
    thaiMeaning: "ความรับผิดชอบ",
    partOfSpeech: "n.",
    examples: [
      "It's your responsibility to lock the door.",
      "Being a manager comes with many responsibilities.",
    ],
    category: "work-business",
  },
  {
    word: "salary",
    phonetic: "/ˈsæləri/",
    thaiMeaning: "เงินเดือน",
    partOfSpeech: "n.",
    examples: ["She earns a good salary.", "My salary is paid monthly."],
    category: "work-business",
  },
  {
    word: "schedule",
    phonetic: "/ˈʃedjuːl/",
    thaiMeaning: "ตารางเวลา",
    partOfSpeech: "n./v.",
    examples: [
      "What's your schedule for today?",
      "The meeting is scheduled for 2 pm.",
    ],
    category: "work-business",
  },
  {
    word: "appointment",
    phonetic: "/əˈpɔɪntmənt/",
    thaiMeaning: "การนัดหมาย",
    partOfSpeech: "n.",
    examples: [
      "I have a doctor's appointment at 10.",
      "Let's make an appointment for next week.",
    ],
    category: "work-business",
  },
  {
    word: "attend",
    phonetic: "/əˈtend/",
    thaiMeaning: "เข้าร่วม",
    partOfSpeech: "v.",
    examples: [
      "Will you attend the meeting?",
      "All students must attend the class.",
    ],
    category: "work-business",
  },
  {
    word: "benefit",
    phonetic: "/ˈbenɪfɪt/",
    thaiMeaning: "ผลประโยชน์",
    partOfSpeech: "n.",
    examples: [
      "What are the benefits of this job?",
      "Exercise has many health benefits.",
    ],
    category: "work-business",
  },
  {
    word: "contract",
    phonetic: "/ˈkɒntrækt/",
    thaiMeaning: "สัญญา",
    partOfSpeech: "n.",
    examples: [
      "Please read the contract carefully.",
      "She signed a two-year contract.",
    ],
    category: "work-business",
  },
  {
    word: "employ",
    phonetic: "/ɪmˈplɔɪ/",
    thaiMeaning: "จ้าง",
    partOfSpeech: "v.",
    examples: [
      "The company employs over 1000 people.",
      "He is employed as a software engineer.",
    ],
    category: "work-business",
  },
  {
    word: "income",
    phonetic: "/ˈɪnkʌm/",
    thaiMeaning: "รายได้",
    partOfSpeech: "n.",
    examples: [
      "I need a steady income.",
      "Her income has increased this year.",
    ],
    category: "work-business",
  },
  {
    word: "interview",
    phonetic: "/ˈɪntəvjuː/",
    thaiMeaning: "สัมภาษณ์",
    partOfSpeech: "n./v.",
    examples: [
      "I have a job interview tomorrow.",
      "They interviewed several candidates.",
    ],
    category: "work-business",
  },
  {
    word: "negotiate",
    phonetic: "/nɪˈɡəʊʃieɪt/",
    thaiMeaning: "เจรจา",
    partOfSpeech: "v.",
    examples: [
      "We need to negotiate the terms.",
      "She is good at negotiating.",
    ],
    category: "work-business",
  },
  {
    word: "promote",
    phonetic: "/prəˈməʊt/",
    thaiMeaning: "เลื่อนตำแหน่ง",
    partOfSpeech: "v.",
    examples: [
      "He was promoted to manager.",
      "They are promoting their new product.",
    ],
    category: "work-business",
  },
  {
    word: "resign",
    phonetic: "/rɪˈzaɪn/",
    thaiMeaning: "ลาออก",
    partOfSpeech: "v.",
    examples: [
      "She decided to resign from her job.",
      "He resigned as director last month.",
    ],
    category: "work-business",
  },
  {
    word: "task",
    phonetic: "/tɑːsk/",
    thaiMeaning: "งาน, ภารกิจ",
    partOfSpeech: "n.",
    examples: [
      "I have a lot of tasks to complete.",
      "The first task is to clean the room.",
    ],
    category: "work-business",
  },
  {
    word: "training",
    phonetic: "/ˈtreɪnɪŋ/",
    thaiMeaning: "การฝึกอบรม",
    partOfSpeech: "n.",
    examples: [
      "New employees get two weeks of training.",
      "She is training to be a nurse.",
    ],
    category: "work-business",
  },
  {
    word: "career",
    phonetic: "/kəˈrɪə/",
    thaiMeaning: "อาชีพ",
    partOfSpeech: "n.",
    examples: [
      "She is building a career in law.",
      "I want to change my career path.",
    ],
    category: "work-business",
  },
  {
    word: "overtime",
    phonetic: "/ˈəʊvətaɪm/",
    thaiMeaning: "ทำงานล่วงเวลา",
    partOfSpeech: "n.",
    examples: [
      "I worked overtime to finish the project.",
      "Do you get paid for overtime?",
    ],
    category: "work-business",
  },

  // ─── Health (20) ──────────────────────────────────────────
  {
    word: "breath",
    phonetic: "/breθ/",
    thaiMeaning: "ลมหายใจ",
    partOfSpeech: "n.",
    examples: [
      "Take a deep breath and relax.",
      "I'm out of breath from running.",
    ],
    category: "health",
  },
  {
    word: "exhausted",
    phonetic: "/ɪɡˈzɔːstɪd/",
    thaiMeaning: "เหนื่อยมาก",
    partOfSpeech: "adj.",
    examples: [
      "I'm exhausted after the long trip.",
      "She looked exhausted and pale.",
    ],
    category: "health",
  },
  {
    word: "medicine",
    phonetic: "/ˈmedsn/",
    thaiMeaning: "ยา",
    partOfSpeech: "n.",
    examples: [
      "Take this medicine twice a day.",
      "Modern medicine has saved many lives.",
    ],
    category: "health",
  },
  {
    word: "suffer",
    phonetic: "/ˈsʌfə/",
    thaiMeaning: "ทนทุกข์, ประสบ",
    partOfSpeech: "v.",
    examples: [
      "He suffers from back pain.",
      "Many people suffer from allergies.",
    ],
    category: "health",
  },
  {
    word: "symptom",
    phonetic: "/ˈsɪmptəm/",
    thaiMeaning: "อาการ",
    partOfSpeech: "n.",
    examples: [
      "What are the symptoms of a cold?",
      "Fever is a common symptom of infection.",
    ],
    category: "health",
  },
  {
    word: "treatment",
    phonetic: "/ˈtriːtmənt/",
    thaiMeaning: "การรักษา",
    partOfSpeech: "n.",
    examples: [
      "She is receiving treatment for her condition.",
      "The treatment takes about an hour.",
    ],
    category: "health",
  },
  {
    word: "weigh",
    phonetic: "/weɪ/",
    thaiMeaning: "ชั่งน้ำหนัก",
    partOfSpeech: "v.",
    examples: [
      "How much do you weigh?",
      "Please weigh the vegetables on the scale.",
    ],
    category: "health",
  },
  {
    word: "allergy",
    phonetic: "/ˈælədʒi/",
    thaiMeaning: "โรคภูมิแพ้",
    partOfSpeech: "n.",
    examples: [
      "I have an allergy to peanuts.",
      "Do you have any food allergies?",
    ],
    category: "health",
  },
  {
    word: "bruise",
    phonetic: "/bruːz/",
    thaiMeaning: "รอยฟกช้ำ",
    partOfSpeech: "n.",
    examples: [
      "He has a bruise on his arm.",
      "The bruise will heal in a few days.",
    ],
    category: "health",
  },
  {
    word: "cough",
    phonetic: "/kɒf/",
    thaiMeaning: "ไอ",
    partOfSpeech: "n./v.",
    examples: ["I have a bad cough.", "She couldn't stop coughing all night."],
    category: "health",
  },
  {
    word: "dizzy",
    phonetic: "/ˈdɪzi/",
    thaiMeaning: "เวียนหัว",
    partOfSpeech: "adj.",
    examples: [
      "I feel dizzy when I stand up.",
      "The spinning ride made me dizzy.",
    ],
    category: "health",
  },
  {
    word: "fever",
    phonetic: "/ˈfiːvə/",
    thaiMeaning: "ไข้",
    partOfSpeech: "n.",
    examples: ["She has a high fever.", "Fever is often a sign of infection."],
    category: "health",
  },
  {
    word: "injury",
    phonetic: "/ˈɪndʒəri/",
    thaiMeaning: "อาการบาดเจ็บ",
    partOfSpeech: "n.",
    examples: [
      "He suffered a serious injury in the accident.",
      "The injury will take weeks to heal.",
    ],
    category: "health",
  },
  {
    word: "pharmacy",
    phonetic: "/ˈfɑːməsi/",
    thaiMeaning: "ร้านขายยา",
    partOfSpeech: "n.",
    examples: [
      "Is there a pharmacy nearby?",
      "You can buy this at any pharmacy.",
    ],
    category: "health",
  },
  {
    word: "prescription",
    phonetic: "/prɪˈskrɪpʃn/",
    thaiMeaning: "ใบสั่งยา",
    partOfSpeech: "n.",
    examples: [
      "You need a prescription for this medicine.",
      "The doctor gave me a prescription.",
    ],
    category: "health",
  },
  {
    word: "recover",
    phonetic: "/rɪˈkʌvə/",
    thaiMeaning: "ฟื้นตัว",
    partOfSpeech: "v.",
    examples: [
      "It took her months to recover from the surgery.",
      "He is recovering well at home.",
    ],
    category: "health",
  },
  {
    word: "sore",
    phonetic: "/sɔː/",
    thaiMeaning: "เจ็บ",
    partOfSpeech: "adj.",
    examples: ["I have a sore throat.", "My muscles are sore after exercise."],
    category: "health",
  },
  {
    word: "stomach",
    phonetic: "/ˈstʌmək/",
    thaiMeaning: "ท้อง",
    partOfSpeech: "n.",
    examples: [
      "My stomach hurts after eating too much.",
      "He has a strong stomach.",
    ],
    category: "health",
  },
  {
    word: "surgery",
    phonetic: "/ˈsɜːdʒəri/",
    thaiMeaning: "การผ่าตัด",
    partOfSpeech: "n.",
    examples: ["She had surgery on her knee.", "The surgery was successful."],
    category: "health",
  },
  {
    word: "wound",
    phonetic: "/wuːnd/",
    thaiMeaning: "บาดแผล",
    partOfSpeech: "n.",
    examples: [
      "The wound is healing slowly.",
      "She cleaned the wound carefully.",
    ],
    category: "health",
  },

  // ─── Education (18) ───────────────────────────────────────
  {
    word: "concentrate",
    phonetic: "/ˈkɒnsntreɪt/",
    thaiMeaning: "มีสมาธิ",
    partOfSpeech: "v.",
    examples: [
      "I can't concentrate with all this noise.",
      "Try to concentrate on your work.",
    ],
    category: "education",
  },
  {
    word: "degree",
    phonetic: "/dɪˈɡriː/",
    thaiMeaning: "ปริญญา",
    partOfSpeech: "n.",
    examples: [
      "She has a degree in biology.",
      "I'm studying for my master's degree.",
    ],
    category: "education",
  },
  {
    word: "improve",
    phonetic: "/ɪmˈpruːv/",
    thaiMeaning: "ปรับปรุง, พัฒนา",
    partOfSpeech: "v.",
    examples: [
      "I want to improve my English skills.",
      "Your work has really improved recently.",
    ],
    category: "education",
  },
  {
    word: "knowledge",
    phonetic: "/ˈnɒlɪdʒ/",
    thaiMeaning: "ความรู้",
    partOfSpeech: "n.",
    examples: [
      "He has a lot of knowledge about history.",
      "Knowledge is power.",
    ],
    category: "education",
  },
  {
    word: "struggle",
    phonetic: "/ˈstrʌɡl/",
    thaiMeaning: "พยายามอย่างหนัก",
    partOfSpeech: "v.",
    examples: [
      "I struggle with maths sometimes.",
      "She is struggling to understand the text.",
    ],
    category: "education",
  },
  {
    word: "assignment",
    phonetic: "/əˈsaɪnmənt/",
    thaiMeaning: "งานที่ได้รับมอบหมาย",
    partOfSpeech: "n.",
    examples: [
      "Have you finished your assignment?",
      "The teacher gave us a difficult assignment.",
    ],
    category: "education",
  },
  {
    word: "certificate",
    phonetic: "/səˈtɪfɪkət/",
    thaiMeaning: "ใบรับรอง",
    partOfSpeech: "n.",
    examples: [
      "She received a certificate of achievement.",
      "Do you have a teaching certificate?",
    ],
    category: "education",
  },
  {
    word: "course",
    phonetic: "/kɔːs/",
    thaiMeaning: "หลักสูตร",
    partOfSpeech: "n.",
    examples: [
      "I'm taking a photography course.",
      "The course starts in September.",
    ],
    category: "education",
  },
  {
    word: "examination",
    phonetic: "/ɪɡˌzæmɪˈneɪʃn/",
    thaiMeaning: "การสอบ",
    partOfSpeech: "n.",
    examples: [
      "The final examination is next week.",
      "She passed the entrance examination.",
    ],
    category: "education",
  },
  {
    word: "graduate",
    phonetic: "/ˈɡrædʒueɪt/",
    thaiMeaning: "จบการศึกษา",
    partOfSpeech: "v./n.",
    examples: [
      "He graduated from university last year.",
      "She's a recent graduate.",
    ],
    category: "education",
  },
  {
    word: "lecture",
    phonetic: "/ˈlektʃə/",
    thaiMeaning: "การบรรยาย",
    partOfSpeech: "n.",
    examples: [
      "The professor gave an interesting lecture.",
      "I fell asleep during the lecture.",
    ],
    category: "education",
  },
  {
    word: "literature",
    phonetic: "/ˈlɪtrətʃə/",
    thaiMeaning: "วรรณกรรม",
    partOfSpeech: "n.",
    examples: [
      "She is studying English literature.",
      "I enjoy reading classic literature.",
    ],
    category: "education",
  },
  {
    word: "research",
    phonetic: "/rɪˈsɜːtʃ/",
    thaiMeaning: "งานวิจัย",
    partOfSpeech: "n./v.",
    examples: [
      "He is doing research on cancer treatment.",
      "I need to research this topic before writing.",
    ],
    category: "education",
  },
  {
    word: "scholarship",
    phonetic: "/ˈskɒləʃɪp/",
    thaiMeaning: "ทุนการศึกษา",
    partOfSpeech: "n.",
    examples: [
      "She won a scholarship to study abroad.",
      "The scholarship covers all tuition fees.",
    ],
    category: "education",
  },
  {
    word: "semester",
    phonetic: "/sɪˈmestə/",
    thaiMeaning: "ภาคการศึกษา",
    partOfSpeech: "n.",
    examples: [
      "The new semester starts in January.",
      "How many courses are you taking this semester?",
    ],
    category: "education",
  },
  {
    word: "skill",
    phonetic: "/skɪl/",
    thaiMeaning: "ทักษะ",
    partOfSpeech: "n.",
    examples: [
      "Communication is an important skill.",
      "She has great computer skills.",
    ],
    category: "education",
  },
  {
    word: "tuition",
    phonetic: "/tjuˈɪʃn/",
    thaiMeaning: "ค่าเล่าเรียน",
    partOfSpeech: "n.",
    examples: [
      "The tuition at this school is very expensive.",
      "How much is the tuition fee?",
    ],
    category: "education",
  },
  {
    word: "tutor",
    phonetic: "/ˈtjuːtə/",
    thaiMeaning: "ครูสอนพิเศษ",
    partOfSpeech: "n./v.",
    examples: [
      "My tutor helps me with chemistry.",
      "She tutors students in her spare time.",
    ],
    category: "education",
  },

  // ─── Technology (18) ──────────────────────────────────────
  {
    word: "access",
    phonetic: "/ˈækses/",
    thaiMeaning: "เข้าถึง",
    partOfSpeech: "n./v.",
    examples: [
      "Do you have access to the internet?",
      "Only staff can access this room.",
    ],
    category: "technology",
  },
  {
    word: "connect",
    phonetic: "/kəˈnekt/",
    thaiMeaning: "เชื่อมต่อ",
    partOfSpeech: "v.",
    examples: [
      "I can't connect to the Wi-Fi.",
      "The printer is connected to my computer.",
    ],
    category: "technology",
  },
  {
    word: "device",
    phonetic: "/dɪˈvaɪs/",
    thaiMeaning: "อุปกรณ์",
    partOfSpeech: "n.",
    examples: [
      "This device can measure your heart rate.",
      "Please turn off all electronic devices.",
    ],
    category: "technology",
  },
  {
    word: "download",
    phonetic: "/ˌdaʊnˈləʊd/",
    thaiMeaning: "ดาวน์โหลด",
    partOfSpeech: "v.",
    examples: [
      "I need to download the file first.",
      "The download speed is very slow.",
    ],
    category: "technology",
  },
  {
    word: "search",
    phonetic: "/sɜːtʃ/",
    thaiMeaning: "ค้นหา",
    partOfSpeech: "v./n.",
    examples: [
      "Let me search for the answer online.",
      "The search took only a few seconds.",
    ],
    category: "technology",
  },
  {
    word: "update",
    phonetic: "/ʌpˈdeɪt/",
    thaiMeaning: "อัปเดต",
    partOfSpeech: "v./n.",
    examples: [
      "You should update your software regularly.",
      "There's a new update available.",
    ],
    category: "technology",
  },
  {
    word: "battery",
    phonetic: "/ˈbætəri/",
    thaiMeaning: "แบตเตอรี่",
    partOfSpeech: "n.",
    examples: ["My battery is running low.", "How long does the battery last?"],
    category: "technology",
  },
  {
    word: "browser",
    phonetic: "/ˈbraʊzə/",
    thaiMeaning: "เบราว์เซอร์",
    partOfSpeech: "n.",
    examples: [
      "Which web browser do you use?",
      "The page won't load in my browser.",
    ],
    category: "technology",
  },
  {
    word: "delete",
    phonetic: "/dɪˈliːt/",
    thaiMeaning: "ลบ",
    partOfSpeech: "v.",
    examples: [
      "I accidentally deleted the file.",
      "Please delete my old account.",
    ],
    category: "technology",
  },
  {
    word: "install",
    phonetic: "/ɪnˈstɔːl/",
    thaiMeaning: "ติดตั้ง",
    partOfSpeech: "v.",
    examples: [
      "Can you install this program for me?",
      "The app is easy to install.",
    ],
    category: "technology",
  },
  {
    word: "password",
    phonetic: "/ˈpɑːswɜːd/",
    thaiMeaning: "รหัสผ่าน",
    partOfSpeech: "n.",
    examples: [
      "Don't share your password with anyone.",
      "I forgot my password again.",
    ],
    category: "technology",
  },
  {
    word: "screen",
    phonetic: "/skriːn/",
    thaiMeaning: "หน้าจอ",
    partOfSpeech: "n.",
    examples: [
      "The screen is cracked.",
      "He spends too much time in front of the screen.",
    ],
    category: "technology",
  },
  {
    word: "software",
    phonetic: "/ˈsɒftweə/",
    thaiMeaning: "ซอฟต์แวร์",
    partOfSpeech: "n.",
    examples: [
      "This software is very easy to use.",
      "We need to update our software.",
    ],
    category: "technology",
  },
  {
    word: "storage",
    phonetic: "/ˈstɔːrɪdʒ/",
    thaiMeaning: "พื้นที่จัดเก็บ",
    partOfSpeech: "n.",
    examples: [
      "I'm running out of storage on my phone.",
      "Cloud storage is very convenient.",
    ],
    category: "technology",
  },
  {
    word: "upload",
    phonetic: "/ʌpˈləʊd/",
    thaiMeaning: "อัปโหลด",
    partOfSpeech: "v.",
    examples: ["I'll upload the photos later.", "The video is uploading now."],
    category: "technology",
  },
  {
    word: "virus",
    phonetic: "/ˈvaɪrəs/",
    thaiMeaning: "ไวรัส",
    partOfSpeech: "n.",
    examples: [
      "My computer has a virus.",
      "You should install anti-virus software.",
    ],
    category: "technology",
  },
  {
    word: "wireless",
    phonetic: "/ˈwaɪələs/",
    thaiMeaning: "ไร้สาย",
    partOfSpeech: "adj.",
    examples: [
      "Do you have wireless internet?",
      "I bought a wireless charger.",
    ],
    category: "technology",
  },
  {
    word: "network",
    phonetic: "/ˈnetwɜːk/",
    thaiMeaning: "เครือข่าย",
    partOfSpeech: "n.",
    examples: [
      "The network is down again.",
      "She has a strong professional network.",
    ],
    category: "technology",
  },

  // ─── Emotions (22) ────────────────────────────────────────
  {
    word: "anxious",
    phonetic: "/ˈæŋkʃəs/",
    thaiMeaning: "กังวล",
    partOfSpeech: "adj.",
    examples: [
      "I'm anxious about the exam results.",
      "She felt anxious before the interview.",
    ],
    category: "emotions",
  },
  {
    word: "confident",
    phonetic: "/ˈkɒnfɪdənt/",
    thaiMeaning: "มั่นใจ",
    partOfSpeech: "adj.",
    examples: [
      "I'm confident that we can win.",
      "She seems very confident about her presentation.",
    ],
    category: "emotions",
  },
  {
    word: "disappointed",
    phonetic: "/ˌdɪsəˈpɔɪntɪd/",
    thaiMeaning: "ผิดหวัง",
    partOfSpeech: "adj.",
    examples: [
      "I was disappointed by the results.",
      "Don't be disappointed — you did your best.",
    ],
    category: "emotions",
  },
  {
    word: "embarrassed",
    phonetic: "/ɪmˈbærəst/",
    thaiMeaning: "อาย",
    partOfSpeech: "adj.",
    examples: [
      "I felt embarrassed when I fell over.",
      "She was too embarrassed to speak.",
    ],
    category: "emotions",
  },
  {
    word: "grateful",
    phonetic: "/ˈɡreɪtfl/",
    thaiMeaning: "กตัญญู, ขอบคุณ",
    partOfSpeech: "adj.",
    examples: [
      "I'm so grateful for your help.",
      "She felt grateful for the opportunity.",
    ],
    category: "emotions",
  },
  {
    word: "lonely",
    phonetic: "/ˈləʊnli/",
    thaiMeaning: "เหงา",
    partOfSpeech: "adj.",
    examples: [
      "I feel lonely when you're not here.",
      "He was lonely after moving to a new city.",
    ],
    category: "emotions",
  },
  {
    word: "relieved",
    phonetic: "/rɪˈliːvd/",
    thaiMeaning: "โล่งใจ",
    partOfSpeech: "adj.",
    examples: [
      "I was relieved to hear the good news.",
      "She felt relieved when the test was over.",
    ],
    category: "emotions",
  },
  {
    word: "satisfied",
    phonetic: "/ˈsætɪsfaɪd/",
    thaiMeaning: "พอใจ",
    partOfSpeech: "adj.",
    examples: [
      "Are you satisfied with the results?",
      "I'm not satisfied with my performance.",
    ],
    category: "emotions",
  },
  {
    word: "annoyed",
    phonetic: "/əˈnɔɪd/",
    thaiMeaning: "รำคาญ",
    partOfSpeech: "adj.",
    examples: [
      "I'm annoyed by the constant noise.",
      "She looked annoyed when I was late.",
    ],
    category: "emotions",
  },
  {
    word: "brave",
    phonetic: "/breɪv/",
    thaiMeaning: "กล้าหาญ",
    partOfSpeech: "adj.",
    examples: [
      "You're so brave for trying that.",
      "The brave firefighter saved the child.",
    ],
    category: "emotions",
  },
  {
    word: "curious",
    phonetic: "/ˈkjʊəriəs/",
    thaiMeaning: "อยากรู้อยากเห็น",
    partOfSpeech: "adj.",
    examples: [
      "I'm curious about your new project.",
      "Children are naturally curious about the world.",
    ],
    category: "emotions",
  },
  {
    word: "depressed",
    phonetic: "/dɪˈprest/",
    thaiMeaning: "หดหู่",
    partOfSpeech: "adj.",
    examples: [
      "She felt depressed after losing her job.",
      "He's been depressed for several months.",
    ],
    category: "emotions",
  },
  {
    word: "enthusiastic",
    phonetic: "/ɪnˌθjuːziˈæstɪk/",
    thaiMeaning: "กระตือรือร้น",
    partOfSpeech: "adj.",
    examples: [
      "The students were enthusiastic about the trip.",
      "She's very enthusiastic about her work.",
    ],
    category: "emotions",
  },
  {
    word: "furious",
    phonetic: "/ˈfjʊəriəs/",
    thaiMeaning: "โมโหมาก",
    partOfSpeech: "adj.",
    examples: [
      "He was furious when he found out the truth.",
      "The teacher was furious with the students.",
    ],
    category: "emotions",
  },
  {
    word: "guilty",
    phonetic: "/ˈɡɪlti/",
    thaiMeaning: "รู้สึกผิด",
    partOfSpeech: "adj.",
    examples: [
      "I felt guilty about lying to her.",
      "The jury found him guilty.",
    ],
    category: "emotions",
  },
  {
    word: "jealous",
    phonetic: "/ˈdʒeləs/",
    thaiMeaning: "อิจฉา",
    partOfSpeech: "adj.",
    examples: [
      "Don't be jealous of her success.",
      "He gets jealous when she talks to other guys.",
    ],
    category: "emotions",
  },
  {
    word: "nervous",
    phonetic: "/ˈnɜːvəs/",
    thaiMeaning: "ประหม่า",
    partOfSpeech: "adj.",
    examples: [
      "I always get nervous before a presentation.",
      "She looked nervous waiting for the results.",
    ],
    category: "emotions",
  },
  {
    word: "patient",
    phonetic: "/ˈpeɪʃnt/",
    thaiMeaning: "อดทน",
    partOfSpeech: "adj.",
    examples: [
      "Please be patient — the doctor will see you soon.",
      "She is very patient with children.",
    ],
    category: "emotions",
  },
  {
    word: "proud",
    phonetic: "/praʊd/",
    thaiMeaning: "ภูมิใจ",
    partOfSpeech: "adj.",
    examples: [
      "I'm very proud of my daughter.",
      "She felt proud of her achievement.",
    ],
    category: "emotions",
  },
  {
    word: "upset",
    phonetic: "/ʌpˈset/",
    thaiMeaning: "เสียใจ, ไม่พอใจ",
    partOfSpeech: "adj.",
    examples: [
      "He was upset when his toy broke.",
      "Don't get upset about small things.",
    ],
    category: "emotions",
  },
  {
    word: "worried",
    phonetic: "/ˈwʌrid/",
    thaiMeaning: "กังวล",
    partOfSpeech: "adj.",
    examples: [
      "I'm worried about my mother's health.",
      "You look worried — is something wrong?",
    ],
    category: "emotions",
  },
  {
    word: "ashamed",
    phonetic: "/əˈʃeɪmd/",
    thaiMeaning: "อับอาย",
    partOfSpeech: "adj.",
    examples: [
      "You should be ashamed of your behavior.",
      "He felt ashamed for telling a lie.",
    ],
    category: "emotions",
  },

  // ─── Nature (16) ──────────────────────────────────────────
  {
    word: "climate",
    phonetic: "/ˈklaɪmət/",
    thaiMeaning: "สภาพอากาศ",
    partOfSpeech: "n.",
    examples: [
      "The climate is changing rapidly.",
      "Thailand has a tropical climate.",
    ],
    category: "nature",
  },
  {
    word: "environment",
    phonetic: "/ɪnˈvaɪrənmənt/",
    thaiMeaning: "สิ่งแวดล้อม",
    partOfSpeech: "n.",
    examples: [
      "We must protect the environment.",
      "Growing up in a supportive environment is important.",
    ],
    category: "nature",
  },
  {
    word: "forecast",
    phonetic: "/ˈfɔːkɑːst/",
    thaiMeaning: "พยากรณ์",
    partOfSpeech: "n./v.",
    examples: [
      "The weather forecast says it will rain.",
      "They forecast a cold winter ahead.",
    ],
    category: "nature",
  },
  {
    word: "scenery",
    phonetic: "/ˈsiːnəri/",
    thaiMeaning: "ทิวทัศน์",
    partOfSpeech: "n.",
    examples: [
      "The scenery in the mountains is beautiful.",
      "We stopped to enjoy the scenery.",
    ],
    category: "nature",
  },
  {
    word: "temperature",
    phonetic: "/ˈtemprətʃə/",
    thaiMeaning: "อุณหภูมิ",
    partOfSpeech: "n.",
    examples: [
      "The temperature dropped below zero.",
      "What's the temperature today?",
    ],
    category: "nature",
  },
  {
    word: "weather",
    phonetic: "/ˈweðə/",
    thaiMeaning: "สภาพอากาศ",
    partOfSpeech: "n.",
    examples: [
      "The weather is lovely today.",
      "Bad weather delayed the flight.",
    ],
    category: "nature",
  },
  {
    word: "coast",
    phonetic: "/kəʊst/",
    thaiMeaning: "ชายฝั่ง",
    partOfSpeech: "n.",
    examples: ["They live on the west coast.", "We drove along the coast."],
    category: "nature",
  },
  {
    word: "earthquake",
    phonetic: "/ˈɜːθkweɪk/",
    thaiMeaning: "แผ่นดินไหว",
    partOfSpeech: "n.",
    examples: [
      "The earthquake destroyed many buildings.",
      "Did you feel the earthquake this morning?",
    ],
    category: "nature",
  },
  {
    word: "flood",
    phonetic: "/flʌd/",
    thaiMeaning: "น้ำท่วม",
    partOfSpeech: "n./v.",
    examples: [
      "The flood damaged many homes.",
      "Heavy rain caused the river to flood.",
    ],
    category: "nature",
  },
  {
    word: "humidity",
    phonetic: "/hjuːˈmɪdəti/",
    thaiMeaning: "ความชื้น",
    partOfSpeech: "n.",
    examples: [
      "The humidity is very high today.",
      "High humidity makes it feel hotter.",
    ],
    category: "nature",
  },
  {
    word: "landscape",
    phonetic: "/ˈlændskeɪp/",
    thaiMeaning: "ทิวทัศน์",
    partOfSpeech: "n.",
    examples: [
      "The landscape here is stunning.",
      "He painted the mountain landscape.",
    ],
    category: "nature",
  },
  {
    word: "ocean",
    phonetic: "/ˈəʊʃn/",
    thaiMeaning: "มหาสมุทร",
    partOfSpeech: "n.",
    examples: [
      "They sailed across the ocean.",
      "The Pacific Ocean is the largest ocean.",
    ],
    category: "nature",
  },
  {
    word: "pollution",
    phonetic: "/pəˈluːʃn/",
    thaiMeaning: "มลพิษ",
    partOfSpeech: "n.",
    examples: [
      "Air pollution is a serious problem.",
      "The river is full of pollution.",
    ],
    category: "nature",
  },
  {
    word: "thunder",
    phonetic: "/ˈθʌndə/",
    thaiMeaning: "ฟ้าร้อง",
    partOfSpeech: "n.",
    examples: [
      "We could hear thunder in the distance.",
      "The thunder was very loud last night.",
    ],
    category: "nature",
  },
  {
    word: "valley",
    phonetic: "/ˈvæli/",
    thaiMeaning: "หุบเขา",
    partOfSpeech: "n.",
    examples: [
      "The village is located in a valley.",
      "We walked through the beautiful green valley.",
    ],
    category: "nature",
  },
  {
    word: "wildlife",
    phonetic: "/ˈwaɪldlaɪf/",
    thaiMeaning: "สัตว์ป่า",
    partOfSpeech: "n.",
    examples: [
      "The park is home to diverse wildlife.",
      "We saw some amazing wildlife on our trip.",
    ],
    category: "nature",
  },

  // ─── Shopping (18) ────────────────────────────────────────
  {
    word: "afford",
    phonetic: "/əˈfɔːd/",
    thaiMeaning: "สามารถจ่ายได้",
    partOfSpeech: "v.",
    examples: [
      "I can't afford a new car right now.",
      "Can we afford to go on holiday this year?",
    ],
    category: "shopping",
  },
  {
    word: "bargain",
    phonetic: "/ˈbɑːɡɪn/",
    thaiMeaning: "ต่อรอง, ของถูก",
    partOfSpeech: "n./v.",
    examples: [
      "I got this jacket at a bargain price.",
      "She loves to bargain at the market.",
    ],
    category: "shopping",
  },
  {
    word: "discount",
    phonetic: "/ˈdɪskaʊnt/",
    thaiMeaning: "ส่วนลด",
    partOfSpeech: "n.",
    examples: [
      "Is there a discount for students?",
      "They're offering a 20% discount.",
    ],
    category: "shopping",
  },
  {
    word: "exchange",
    phonetic: "/ɪksˈtʃeɪndʒ/",
    thaiMeaning: "แลกเปลี่ยน",
    partOfSpeech: "v./n.",
    examples: [
      "Can I exchange this for a larger size?",
      "The exchange rate is very good today.",
    ],
    category: "shopping",
  },
  {
    word: "refund",
    phonetic: "/ˈriːfʌnd/",
    thaiMeaning: "เงินคืน",
    partOfSpeech: "n./v.",
    examples: [
      "I want a refund for this faulty item.",
      "The store refused to refund my money.",
    ],
    category: "shopping",
  },
  {
    word: "receipt",
    phonetic: "/rɪˈsiːt/",
    thaiMeaning: "ใบเสร็จ",
    partOfSpeech: "n.",
    examples: [
      "Keep your receipt for exchanges.",
      "Can I have a receipt please?",
    ],
    category: "shopping",
  },
  {
    word: "brand",
    phonetic: "/brænd/",
    thaiMeaning: "ยี่ห้อ",
    partOfSpeech: "n.",
    examples: [
      "Which brand of shoes do you prefer?",
      "This is a well-known brand.",
    ],
    category: "shopping",
  },
  {
    word: "catalogue",
    phonetic: "/ˈkætəlɒɡ/",
    thaiMeaning: "แคตตาล็อก",
    partOfSpeech: "n.",
    examples: [
      "I ordered the dress from a catalogue.",
      "Browse our online catalogue for more options.",
    ],
    category: "shopping",
  },
  {
    word: "customer",
    phonetic: "/ˈkʌstəmə/",
    thaiMeaning: "ลูกค้า",
    partOfSpeech: "n.",
    examples: ["The customer is always right.", "We value every customer."],
    category: "shopping",
  },
  {
    word: "guarantee",
    phonetic: "/ˌɡærənˈtiː/",
    thaiMeaning: "การรับประกัน",
    partOfSpeech: "n./v.",
    examples: [
      "This product comes with a guarantee.",
      "I can guarantee you'll love it.",
    ],
    category: "shopping",
  },
  {
    word: "luxury",
    phonetic: "/ˈlʌkʃəri/",
    thaiMeaning: "หรูหรา",
    partOfSpeech: "n./adj.",
    examples: [
      "Staying in that hotel is a real luxury.",
      "She enjoys luxury brands.",
    ],
    category: "shopping",
  },
  {
    word: "purchase",
    phonetic: "/ˈpɜːtʃəs/",
    thaiMeaning: "ซื้อ",
    partOfSpeech: "v./n.",
    examples: [
      "When did you purchase this item?",
      "Thank you for your purchase.",
    ],
    category: "shopping",
  },
  {
    word: "quality",
    phonetic: "/ˈkwɒləti/",
    thaiMeaning: "คุณภาพ",
    partOfSpeech: "n.",
    examples: [
      "We only sell high-quality products.",
      "The quality of this bag is excellent.",
    ],
    category: "shopping",
  },
  {
    word: "size",
    phonetic: "/saɪz/",
    thaiMeaning: "ขนาด",
    partOfSpeech: "n.",
    examples: ["What size do you wear?", "Do you have this in a smaller size?"],
    category: "shopping",
  },
  {
    word: "store",
    phonetic: "/stɔː/",
    thaiMeaning: "ร้านค้า",
    partOfSpeech: "n.",
    examples: [
      "There's a new store at the mall.",
      "I bought this at the department store.",
    ],
    category: "shopping",
  },
  {
    word: "sale",
    phonetic: "/seɪl/",
    thaiMeaning: "การขาย, การลดราคา",
    partOfSpeech: "n.",
    examples: [
      "The summer sale starts next week.",
      "This item is not for sale.",
    ],
    category: "shopping",
  },
  {
    word: "expensive",
    phonetic: "/ɪkˈspensɪv/",
    thaiMeaning: "แพง",
    partOfSpeech: "adj.",
    examples: [
      "This bag is very expensive.",
      "Tokyo is an expensive city to live in.",
    ],
    category: "shopping",
  },
  {
    word: "affordable",
    phonetic: "/əˈfɔːdəbl/",
    thaiMeaning: "ราคาไม่แพง",
    partOfSpeech: "adj.",
    examples: [
      "They offer affordable housing.",
      "This restaurant is very affordable.",
    ],
    category: "shopping",
  },

  // ─── People (20) ──────────────────────────────────────────
  {
    word: "acquaintance",
    phonetic: "/əˈkweɪntəns/",
    thaiMeaning: "คนรู้จัก",
    partOfSpeech: "n.",
    examples: [
      "He's not a friend, just an acquaintance.",
      "I made the acquaintance of her brother.",
    ],
    category: "people",
  },
  {
    word: "couple",
    phonetic: "/ˈkʌpl/",
    thaiMeaning: "คู่, สองสาม",
    partOfSpeech: "n.",
    examples: [
      "They are a lovely couple.",
      "I met a couple of friends for lunch.",
    ],
    category: "people",
  },
  {
    word: "generous",
    phonetic: "/ˈdʒenərəs/",
    thaiMeaning: "ใจกว้าง",
    partOfSpeech: "adj.",
    examples: [
      "She is very generous with her time.",
      "Thank you for your generous donation.",
    ],
    category: "people",
  },
  {
    word: "polite",
    phonetic: "/pəˈlaɪt/",
    thaiMeaning: "สุภาพ",
    partOfSpeech: "adj.",
    examples: [
      "He was very polite to the guests.",
      "It's polite to say thank you.",
    ],
    category: "people",
  },
  {
    word: "reliable",
    phonetic: "/rɪˈlaɪəbl/",
    thaiMeaning: "เชื่อถือได้",
    partOfSpeech: "adj.",
    examples: [
      "She is a reliable friend.",
      "This car is old but still reliable.",
    ],
    category: "people",
  },
  {
    word: "relationship",
    phonetic: "/rɪˈleɪʃnʃɪp/",
    thaiMeaning: "ความสัมพันธ์",
    partOfSpeech: "n.",
    examples: [
      "They have a good relationship.",
      "I'm in a relationship with her.",
    ],
    category: "people",
  },
  {
    word: "celebrity",
    phonetic: "/səˈlebrəti/",
    thaiMeaning: "คนดัง",
    partOfSpeech: "n.",
    examples: [
      "She became a celebrity overnight.",
      "The celebrity signed autographs for fans.",
    ],
    category: "people",
  },
  {
    word: "character",
    phonetic: "/ˈkærəktə/",
    thaiMeaning: "นิสัย, ตัวละคร",
    partOfSpeech: "n.",
    examples: [
      "He has a strong character.",
      "The main character in the movie is very brave.",
    ],
    category: "people",
  },
  {
    word: "community",
    phonetic: "/kəˈmjuːnəti/",
    thaiMeaning: "ชุมชน",
    partOfSpeech: "n.",
    examples: [
      "We live in a small community.",
      "The community came together to help.",
    ],
    category: "people",
  },
  {
    word: "divorce",
    phonetic: "/dɪˈvɔːs/",
    thaiMeaning: "การหย่าร้าง",
    partOfSpeech: "n./v.",
    examples: [
      "They decided to get a divorce.",
      "Her parents divorced when she was young.",
    ],
    category: "people",
  },
  {
    word: "engaged",
    phonetic: "/ɪnˈɡeɪdʒd/",
    thaiMeaning: "หมั้น",
    partOfSpeech: "adj.",
    examples: [
      "They got engaged last month.",
      "She showed me her engagement ring.",
    ],
    category: "people",
  },
  {
    word: "friendship",
    phonetic: "/ˈfrendʃɪp/",
    thaiMeaning: "มิตรภาพ",
    partOfSpeech: "n.",
    examples: [
      "Their friendship has lasted for years.",
      "I value our friendship very much.",
    ],
    category: "people",
  },
  {
    word: "honest",
    phonetic: "/ˈɒnɪst/",
    thaiMeaning: "ซื่อสัตย์",
    partOfSpeech: "adj.",
    examples: ["Please be honest with me.", "He is an honest person."],
    category: "people",
  },
  {
    word: "introduce",
    phonetic: "/ˌɪntrəˈdjuːs/",
    thaiMeaning: "แนะนำ",
    partOfSpeech: "v.",
    examples: [
      "Let me introduce you to my friend.",
      "She introduced herself to the class.",
    ],
    category: "people",
  },
  {
    word: "neighbour",
    phonetic: "/ˈneɪbə/",
    thaiMeaning: "เพื่อนบ้าน",
    partOfSpeech: "n.",
    examples: [
      "Our neighbours are very friendly.",
      "The neighbour complained about the noise.",
    ],
    category: "people",
  },
  {
    word: "relative",
    phonetic: "/ˈrelətɪv/",
    thaiMeaning: "ญาติ",
    partOfSpeech: "n.",
    examples: [
      "I'm staying with relatives in Bangkok.",
      "Many of my relatives live abroad.",
    ],
    category: "people",
  },
  {
    word: "respect",
    phonetic: "/rɪˈspekt/",
    thaiMeaning: "เคารพ",
    partOfSpeech: "n./v.",
    examples: [
      "I have great respect for my parents.",
      "You should respect other people's opinions.",
    ],
    category: "people",
  },
  {
    word: "stranger",
    phonetic: "/ˈstreɪndʒə/",
    thaiMeaning: "คนแปลกหน้า",
    partOfSpeech: "n.",
    examples: ["Don't talk to strangers.", "A stranger helped me find my way."],
    category: "people",
  },
  {
    word: "trust",
    phonetic: "/trʌst/",
    thaiMeaning: "ไว้ใจ",
    partOfSpeech: "n./v.",
    examples: [
      "Trust is important in any relationship.",
      "I trust you with my life.",
    ],
    category: "people",
  },
  {
    word: "volunteer",
    phonetic: "/ˌvɒlənˈtɪə/",
    thaiMeaning: "อาสาสมัคร",
    partOfSpeech: "n./v.",
    examples: [
      "She works as a volunteer at the hospital.",
      "I volunteered to help organize the event.",
    ],
    category: "people",
  },

  // ─── Time (18) ────────────────────────────────────────────
  {
    word: "afterwards",
    phonetic: "/ˈɑːftəwədz/",
    thaiMeaning: "หลังจากนั้น",
    partOfSpeech: "adv.",
    examples: [
      "We went for dinner and afterwards we saw a movie.",
      "Afterwards, I realized my mistake.",
    ],
    category: "time",
  },
  {
    word: "currently",
    phonetic: "/ˈkʌrəntli/",
    thaiMeaning: "ปัจจุบันนี้",
    partOfSpeech: "adv.",
    examples: [
      "I'm currently working on a new project.",
      "She is currently living in London.",
    ],
    category: "time",
  },
  {
    word: "eventually",
    phonetic: "/ɪˈventʃuəli/",
    thaiMeaning: "ในที่สุด",
    partOfSpeech: "adv.",
    examples: [
      "Eventually, he arrived two hours late.",
      "You will eventually get used to it.",
    ],
    category: "time",
  },
  {
    word: "frequently",
    phonetic: "/ˈfriːkwəntli/",
    thaiMeaning: "บ่อย",
    partOfSpeech: "adv.",
    examples: [
      "I frequently visit my grandparents.",
      "This happens more frequently than you'd think.",
    ],
    category: "time",
  },
  {
    word: "immediately",
    phonetic: "/ɪˈmiːdiətli/",
    thaiMeaning: "ทันที",
    partOfSpeech: "adv.",
    examples: [
      "Please leave immediately.",
      "She replied to my message immediately.",
    ],
    category: "time",
  },
  {
    word: "recently",
    phonetic: "/ˈriːsntli/",
    thaiMeaning: "เมื่อเร็วๆนี้",
    partOfSpeech: "adv.",
    examples: [
      "I recently started learning Japanese.",
      "Have you seen any good movies recently?",
    ],
    category: "time",
  },
  {
    word: "annual",
    phonetic: "/ˈænjuəl/",
    thaiMeaning: "ประจำปี",
    partOfSpeech: "adj.",
    examples: [
      "The annual meeting is next week.",
      "They hold an annual music festival.",
    ],
    category: "time",
  },
  {
    word: "century",
    phonetic: "/ˈsentʃəri/",
    thaiMeaning: "ศตวรรษ",
    partOfSpeech: "n.",
    examples: [
      "This building is over a century old.",
      "The 21st century brought many changes.",
    ],
    category: "time",
  },
  {
    word: "decade",
    phonetic: "/ˈdekeɪd/",
    thaiMeaning: "ทศวรรษ",
    partOfSpeech: "n.",
    examples: [
      "She spent a decade working abroad.",
      "The city has changed a lot in the past decade.",
    ],
    category: "time",
  },
  {
    word: "duration",
    phonetic: "/djuˈreɪʃn/",
    thaiMeaning: "ระยะเวลา",
    partOfSpeech: "n.",
    examples: [
      "The duration of the flight is 12 hours.",
      "Please remain seated for the duration of the show.",
    ],
    category: "time",
  },
  {
    word: "forever",
    phonetic: "/fərˈevə/",
    thaiMeaning: "ตลอดกาล",
    partOfSpeech: "adv.",
    examples: [
      "I will love you forever.",
      "The meeting seemed to last forever.",
    ],
    category: "time",
  },
  {
    word: "gradually",
    phonetic: "/ˈɡrædʒuəli/",
    thaiMeaning: "ค่อยๆ",
    partOfSpeech: "adv.",
    examples: [
      "Gradually, the weather got warmer.",
      "She gradually improved her English.",
    ],
    category: "time",
  },
  {
    word: "meanwhile",
    phonetic: "/ˈmiːnwaɪl/",
    thaiMeaning: "ในขณะเดียวกัน",
    partOfSpeech: "adv.",
    examples: [
      "I'll cook dinner. Meanwhile, you can set the table.",
      "Meanwhile, back at the office, things were chaotic.",
    ],
    category: "time",
  },
  {
    word: "permanent",
    phonetic: "/ˈpɜːmənənt/",
    thaiMeaning: "ถาวร",
    partOfSpeech: "adj.",
    examples: ["Is this a permanent arrangement?", "The damage is permanent."],
    category: "time",
  },
  {
    word: "punctual",
    phonetic: "/ˈpʌŋktʃuəl/",
    thaiMeaning: "ตรงเวลา",
    partOfSpeech: "adj.",
    examples: [
      "Please try to be punctual.",
      "She is always punctual for meetings.",
    ],
    category: "time",
  },
  {
    word: "seldom",
    phonetic: "/ˈseldəm/",
    thaiMeaning: "ไม่ค่อย",
    partOfSpeech: "adv.",
    examples: [
      "I seldom eat fast food.",
      "She seldom complains about anything.",
    ],
    category: "time",
  },
  {
    word: "suddenly",
    phonetic: "/ˈsʌdnli/",
    thaiMeaning: "ทันใดนั้น",
    partOfSpeech: "adv.",
    examples: [
      "Suddenly, it started to rain.",
      "The car stopped suddenly in front of me.",
    ],
    category: "time",
  },
  {
    word: "urgent",
    phonetic: "/ˈɜːdʒənt/",
    thaiMeaning: "ด่วน",
    partOfSpeech: "adj.",
    examples: [
      "I need to make an urgent phone call.",
      "There's an urgent matter to discuss.",
    ],
    category: "time",
  },
];

export function getWordsByCategory(category: string): VocabWord[] {
  return OXFORD_WORDS.filter((w) => w.category === category);
}

export function getAllCategories(): string[] {
  const cats = new Set(OXFORD_WORDS.map((w) => w.category));
  return Array.from(cats);
}
